behaviors:
  FishLearning:   # <- must match Behavior Name in Unity
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000   # total training steps before auto-stop
    time_horizon: 128    # how many steps to unroll per agent before updating
    summary_freq: 10000  # how often stats are written to TensorBoard